<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Label="ProjectReferences">
    <ProjectReference Include="..\ETS2LA.Shared\ETS2LA.Shared.csproj" />
    <ProjectReference Include="..\ETS2LA.Backend\ETS2LA.Backend.csproj" />
    <ProjectReference Include="..\ETS2LA.Settings\ETS2LA.Settings.csproj" />
    <ProjectReference Include="..\ETS2LA.Logging\ETS2LA.Logging.csproj" />
    <ProjectReference Include="..\ETS2LA.Notifications\ETS2LA.Notifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

</Project>
