<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Label="ProjectReferences">
    <ProjectReference Include="..\ETS2LA.Shared\ETS2LA.Shared.csproj" />
    <ProjectReference Include="..\ETS2LA.Settings\ETS2LA.Settings.csproj" />
    <ProjectReference Include="..\ETS2LA.Logging\ETS2LA.Logging.csproj" />
    <ProjectReference Include="..\ETS2LA.Controls\ETS2LA.Controls.csproj" />
    <ProjectReference Include="..\ETS2LA.Audio\ETS2LA.Audio.csproj" />
    <ProjectReference Include="..\ETS2LA.Notifications\ETS2LA.Notifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" />
  </ItemGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Unix'">
    <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
  </PropertyGroup>
</Project>
